version: '3'
services:
  web:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9200:9200"
networks:
  webnet: